/* eslint-disable */
// @ts-nocheck
// Auto-generated by TanStack Router.
import { Route as rootRouteImport }       from './routes/__root'
import { Route as IndexRouteImport }      from './routes/index'
import { Route as ApiChatRouteImport }    from './routes/api/chat'
import { Route as ApiSttRouteImport }     from './routes/api/stt'
import { Route as ApiTtsRouteImport }     from './routes/api/tts'
import { Route as ApiVisionRouteImport }  from './routes/api/vision'
import { Route as ApiSimulateRouteImport } from './routes/api/simulate'

const IndexRoute       = IndexRouteImport.update({ id:'/',            path:'/',            getParentRoute:()=>rootRouteImport } as any)
const ApiChatRoute     = ApiChatRouteImport.update({ id:'/api/chat',     path:'/api/chat',     getParentRoute:()=>rootRouteImport } as any)
const ApiSttRoute      = ApiSttRouteImport.update({ id:'/api/stt',      path:'/api/stt',      getParentRoute:()=>rootRouteImport } as any)
const ApiTtsRoute      = ApiTtsRouteImport.update({ id:'/api/tts',      path:'/api/tts',      getParentRoute:()=>rootRouteImport } as any)
const ApiVisionRoute   = ApiVisionRouteImport.update({ id:'/api/vision',   path:'/api/vision',   getParentRoute:()=>rootRouteImport } as any)
const ApiSimulateRoute = ApiSimulateRouteImport.update({ id:'/api/simulate', path:'/api/simulate', getParentRoute:()=>rootRouteImport } as any)

export interface FileRoutesByFullPath {
  '/':'/'; '/api/chat':'/api/chat'; '/api/stt':'/api/stt'; '/api/tts':'/api/tts';
  '/api/vision':'/api/vision'; '/api/simulate':'/api/simulate';
}
export interface FileRouteTypes {
  fileRoutesByFullPath:FileRoutesByFullPath;
  fullPaths:'/'|'/api/chat'|'/api/stt'|'/api/tts'|'/api/vision'|'/api/simulate';
  id:'__root__'|'/'|'/api/chat'|'/api/stt'|'/api/tts'|'/api/vision'|'/api/simulate';
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/':{ id:'/';path:'/';fullPath:'/';preLoaderRoute:typeof IndexRouteImport;parentRoute:typeof rootRouteImport }
    '/api/chat':{ id:'/api/chat';path:'/api/chat';fullPath:'/api/chat';preLoaderRoute:typeof ApiChatRouteImport;parentRoute:typeof rootRouteImport }
    '/api/stt':{ id:'/api/stt';path:'/api/stt';fullPath:'/api/stt';preLoaderRoute:typeof ApiSttRouteImport;parentRoute:typeof rootRouteImport }
    '/api/tts':{ id:'/api/tts';path:'/api/tts';fullPath:'/api/tts';preLoaderRoute:typeof ApiTtsRouteImport;parentRoute:typeof rootRouteImport }
    '/api/vision':{ id:'/api/vision';path:'/api/vision';fullPath:'/api/vision';preLoaderRoute:typeof ApiVisionRouteImport;parentRoute:typeof rootRouteImport }
    '/api/simulate':{ id:'/api/simulate';path:'/api/simulate';fullPath:'/api/simulate';preLoaderRoute:typeof ApiSimulateRouteImport;parentRoute:typeof rootRouteImport }
  }
}

const rootRouteChildren = { IndexRoute, ApiChatRoute, ApiSttRoute, ApiTtsRoute, ApiVisionRoute, ApiSimulateRoute }
export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)._addFileTypes<FileRouteTypes>()
