/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkflowsRouteImport } from './routes/workflows'
import { Route as GhostVisionRouteImport } from './routes/ghost-vision'
import { Route as CoolmationRouteImport } from './routes/coolmation'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiWorkflowRouteImport } from './routes/api/workflow'
import { Route as ApiVisionRouteImport } from './routes/api/vision'
import { Route as ApiVideoStatusRouteImport } from './routes/api/video-status'
import { Route as ApiVideoRouteImport } from './routes/api/video'
import { Route as ApiTtsRouteImport } from './routes/api/tts'
import { Route as ApiSttRouteImport } from './routes/api/stt'
import { Route as ApiSimulateRouteImport } from './routes/api/simulate'
import { Route as ApiSearchRouteImport } from './routes/api/search'
import { Route as ApiImageRouteImport } from './routes/api/image'
import { Route as ApiChatRouteImport } from './routes/api/chat'

const WorkflowsRoute = WorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => rootRouteImport,
} as any)
const GhostVisionRoute = GhostVisionRouteImport.update({
  id: '/ghost-vision',
  path: '/ghost-vision',
  getParentRoute: () => rootRouteImport,
} as any)
const CoolmationRoute = CoolmationRouteImport.update({
  id: '/coolmation',
  path: '/coolmation',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWorkflowRoute = ApiWorkflowRouteImport.update({
  id: '/api/workflow',
  path: '/api/workflow',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVisionRoute = ApiVisionRouteImport.update({
  id: '/api/vision',
  path: '/api/vision',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVideoStatusRoute = ApiVideoStatusRouteImport.update({
  id: '/api/video-status',
  path: '/api/video-status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVideoRoute = ApiVideoRouteImport.update({
  id: '/api/video',
  path: '/api/video',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTtsRoute = ApiTtsRouteImport.update({
  id: '/api/tts',
  path: '/api/tts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSttRoute = ApiSttRouteImport.update({
  id: '/api/stt',
  path: '/api/stt',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSimulateRoute = ApiSimulateRouteImport.update({
  id: '/api/simulate',
  path: '/api/simulate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiImageRoute = ApiImageRouteImport.update({
  id: '/api/image',
  path: '/api/image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/coolmation': typeof CoolmationRoute
  '/ghost-vision': typeof GhostVisionRoute
  '/workflows': typeof WorkflowsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/image': typeof ApiImageRoute
  '/api/search': typeof ApiSearchRoute
  '/api/simulate': typeof ApiSimulateRoute
  '/api/stt': typeof ApiSttRoute
  '/api/tts': typeof ApiTtsRoute
  '/api/video': typeof ApiVideoRoute
  '/api/video-status': typeof ApiVideoStatusRoute
  '/api/vision': typeof ApiVisionRoute
  '/api/workflow': typeof ApiWorkflowRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/coolmation': typeof CoolmationRoute
  '/ghost-vision': typeof GhostVisionRoute
  '/workflows': typeof WorkflowsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/image': typeof ApiImageRoute
  '/api/search': typeof ApiSearchRoute
  '/api/simulate': typeof ApiSimulateRoute
  '/api/stt': typeof ApiSttRoute
  '/api/tts': typeof ApiTtsRoute
  '/api/video': typeof ApiVideoRoute
  '/api/video-status': typeof ApiVideoStatusRoute
  '/api/vision': typeof ApiVisionRoute
  '/api/workflow': typeof ApiWorkflowRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/coolmation': typeof CoolmationRoute
  '/ghost-vision': typeof GhostVisionRoute
  '/workflows': typeof WorkflowsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/image': typeof ApiImageRoute
  '/api/search': typeof ApiSearchRoute
  '/api/simulate': typeof ApiSimulateRoute
  '/api/stt': typeof ApiSttRoute
  '/api/tts': typeof ApiTtsRoute
  '/api/video': typeof ApiVideoRoute
  '/api/video-status': typeof ApiVideoStatusRoute
  '/api/vision': typeof ApiVisionRoute
  '/api/workflow': typeof ApiWorkflowRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/coolmation'
    | '/ghost-vision'
    | '/workflows'
    | '/api/chat'
    | '/api/image'
    | '/api/search'
    | '/api/simulate'
    | '/api/stt'
    | '/api/tts'
    | '/api/video'
    | '/api/video-status'
    | '/api/vision'
    | '/api/workflow'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/coolmation'
    | '/ghost-vision'
    | '/workflows'
    | '/api/chat'
    | '/api/image'
    | '/api/search'
    | '/api/simulate'
    | '/api/stt'
    | '/api/tts'
    | '/api/video'
    | '/api/video-status'
    | '/api/vision'
    | '/api/workflow'
  id:
    | '__root__'
    | '/'
    | '/coolmation'
    | '/ghost-vision'
    | '/workflows'
    | '/api/chat'
    | '/api/image'
    | '/api/search'
    | '/api/simulate'
    | '/api/stt'
    | '/api/tts'
    | '/api/video'
    | '/api/video-status'
    | '/api/vision'
    | '/api/workflow'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CoolmationRoute: typeof CoolmationRoute
  GhostVisionRoute: typeof GhostVisionRoute
  WorkflowsRoute: typeof WorkflowsRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiImageRoute: typeof ApiImageRoute
  ApiSearchRoute: typeof ApiSearchRoute
  ApiSimulateRoute: typeof ApiSimulateRoute
  ApiSttRoute: typeof ApiSttRoute
  ApiTtsRoute: typeof ApiTtsRoute
  ApiVideoRoute: typeof ApiVideoRoute
  ApiVideoStatusRoute: typeof ApiVideoStatusRoute
  ApiVisionRoute: typeof ApiVisionRoute
  ApiWorkflowRoute: typeof ApiWorkflowRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workflows': {
      id: '/workflows'
      path: '/workflows'
      fullPath: '/workflows'
      preLoaderRoute: typeof WorkflowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ghost-vision': {
      id: '/ghost-vision'
      path: '/ghost-vision'
      fullPath: '/ghost-vision'
      preLoaderRoute: typeof GhostVisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coolmation': {
      id: '/coolmation'
      path: '/coolmation'
      fullPath: '/coolmation'
      preLoaderRoute: typeof CoolmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workflow': {
      id: '/api/workflow'
      path: '/api/workflow'
      fullPath: '/api/workflow'
      preLoaderRoute: typeof ApiWorkflowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/vision': {
      id: '/api/vision'
      path: '/api/vision'
      fullPath: '/api/vision'
      preLoaderRoute: typeof ApiVisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/video-status': {
      id: '/api/video-status'
      path: '/api/video-status'
      fullPath: '/api/video-status'
      preLoaderRoute: typeof ApiVideoStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/video': {
      id: '/api/video'
      path: '/api/video'
      fullPath: '/api/video'
      preLoaderRoute: typeof ApiVideoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tts': {
      id: '/api/tts'
      path: '/api/tts'
      fullPath: '/api/tts'
      preLoaderRoute: typeof ApiTtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stt': {
      id: '/api/stt'
      path: '/api/stt'
      fullPath: '/api/stt'
      preLoaderRoute: typeof ApiSttRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/simulate': {
      id: '/api/simulate'
      path: '/api/simulate'
      fullPath: '/api/simulate'
      preLoaderRoute: typeof ApiSimulateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/image': {
      id: '/api/image'
      path: '/api/image'
      fullPath: '/api/image'
      preLoaderRoute: typeof ApiImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CoolmationRoute: CoolmationRoute,
  GhostVisionRoute: GhostVisionRoute,
  WorkflowsRoute: WorkflowsRoute,
  ApiChatRoute: ApiChatRoute,
  ApiImageRoute: ApiImageRoute,
  ApiSearchRoute: ApiSearchRoute,
  ApiSimulateRoute: ApiSimulateRoute,
  ApiSttRoute: ApiSttRoute,
  ApiTtsRoute: ApiTtsRoute,
  ApiVideoRoute: ApiVideoRoute,
  ApiVideoStatusRoute: ApiVideoStatusRoute,
  ApiVisionRoute: ApiVisionRoute,
  ApiWorkflowRoute: ApiWorkflowRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
